---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  formatting-and-quality:
    name: Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Setup
        run: rustup component add clippy rustfmt

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -Dwarnings

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev

      - name: Build and Test
        run: cargo test
